
CREATE TABLE mesas (
                       id_mesa     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       nombre      VARCHAR2(100) NOT NULL,
                       capacidad   NUMBER(3) DEFAULT 10 NOT NULL,
                       id_usuario  NUMBER NOT NULL,
                       CONSTRAINT fk_mesas_usuario
                           FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario) ON DELETE CASCADE
);


CREATE TABLE invitados (
                           id_invitado         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           nombre              VARCHAR2(150) NOT NULL,
                           correo              VARCHAR2(150) NOT NULL,
                           id_mesa             NUMBER NOT NULL,
                           invitacion_enviada  CHAR(1) DEFAULT 'N' NOT NULL,
                           fecha_envio         TIMESTAMP NULL,
                           CONSTRAINT fk_invitados_mesa
                               FOREIGN KEY (id_mesa) REFERENCES mesas (id_mesa) ON DELETE CASCADE,
                           CONSTRAINT chk_invitacion_enviada CHECK (invitacion_enviada IN ('S', 'N'))
);

CREATE INDEX idx_mesas_usuario ON mesas (id_usuario);
CREATE INDEX idx_invitados_mesa ON invitados (id_mesa);
